// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg-e3I6H_wKEEU-1L35NAfaYr8Rrif_iA',
    appId: '1:754854194539:web:87a864a1bfe9032b81302e',
    messagingSenderId: '754854194539',
    projectId: 'quick-notes-637eb',
    authDomain: 'quick-notes-637eb.firebaseapp.com',
    storageBucket: 'quick-notes-637eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvqgVJpjjKPf_QOdfRQHDHWadJ5rIyhhg',
    appId: '1:754854194539:android:4a8042001809d69f81302e',
    messagingSenderId: '754854194539',
    projectId: 'quick-notes-637eb',
    storageBucket: 'quick-notes-637eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApvOiaNZHH_NRIc_u_Q_rzV8AXCOx4bKY',
    appId: '1:754854194539:ios:ee2c2649b97921c481302e',
    messagingSenderId: '754854194539',
    projectId: 'quick-notes-637eb',
    storageBucket: 'quick-notes-637eb.firebasestorage.app',
    iosBundleId: 'com.example.quickNotes',
  );
}
